version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"

  user_service:
    build: ./user_service
    volumes:
      - ./common:/app/common
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - elasticsearch

  hotel_service:
    build: ./hotel_service
    volumes:
      - ./common:/app/common
    ports:
      - "5001:5001"
    depends_on:
      - kafka
      - elasticsearch

  reservation_service:
    build: ./reservation_service
    volumes:
      - ./common:/app/common
    ports:
      - "5002:5002"
    depends_on:
      - kafka
      - elasticsearch

  api_gateway:
    build: ./api_gateway
    volumes:
      - ./common:/app/common
    ports:
      - "5003:5003"
    depends_on:
      - kafka
      - elasticsearch
